import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <img src="/images/unnamed.jpeg" alt="jaeyoung" /> */}
        <Image
          src="/public/images/unnamed.jpeg"
          alt="jaeyoung"
          width={166}
          height={166}
        />

        {/* Image 안생기는 이유 찾기 ? img 가 아니구 next image 컴포넌트를 사용했음에도 불구하고 왜 안생길까 */}
        {/* Image 를 쓰면 좋은 점 Resizing, lazy load, optimazation  */}
        <h1 className={styles.title}>
          Read this Post{" "}
          <Link href="/posts/first-post">
            <a>첫번째 글</a>
          </Link>
          {/* Link 컴포넌트를 이용하면 필요한 내용만 추가적으로 불러온다 */}
          {/* a태그만을 사용할경우 브라우저를 리로드시켜 불필요한 요소들까지 불러오기 때문에 성능상 좋지않다 */}
          {/* 결론 본 서비스 외부 링크로 연결 할때는 <a> tag만 쓰면댐 */}
          {/* Link Component에 스타일을 줄때는 <a> tag에 줘야함  */}
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          <Link href="/posts/second-post">
            <a>두번째 글</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
